pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - files~=README$
    actions:
        comment:
          message: |
            Thanks for contributing in README.md, Have a great journey ahead
            Keep Contributing !!! 🙏
