pull_request_rules:
  - name: Message on opening a PR
    conditions:
      - "files=README"
    actions:
        comment:
            message: Thanks for updating the README.md file🙏, Keep contributing !!
