pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
  - name: message on modifying README.md
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      comment:
        message: Thanks for Contributing in README.md, KEEP CONTRIBUTING 🤍 !!
